### PR TITLE
Add missing options to helper

### PR DESCRIPTION
**Pull request by hexgnu**
Hello there. As I saw in #22 you suggested that someone write a PR to fix the problem.

This adds unique to the available options as well as adds user_agent, say_cheese, ttl, and custom_css_url which are all part of the url2png api.

Thank you for taking your time to look at this and get this merged.

I had to make some changes to get this to work on ruby 2 since it was relying on Rcov which won't work on anything that is > 1.9.x

### CODE REVIEW

**Comment by hoetmaaiers** [comment]
Thank you @hexgnu

**Comment by jagthedrummer** [comment]
@hoetmaaiers Any chance you could bump the version number and publish a new version of the gem to get this change out and available?

**Comment by hoetmaaiers** [comment]
Well this has been many years ago since I have bumped the version. I would happily provide access and permissions to an active user/contributor to facilitate this. Are you interested @jagthedrummer or @hexgnu ?

**Comment by jagthedrummer** [comment]
@hoetmaaiers Sure, I could bump the version and publish the gem if you can give me the access to do so.

**Comment by hoetmaaiers** [comment]
Ok, I invited you on Github and Rubygems. Thanks for helping a hand.

**Comment by jagthedrummer** [comment]
Thanks for setting me up to do that @hoetmaaiers. I've bumped the version and published a new gem. 🙇

**Comment by hoetmaaiers** [comment]
Great, thank you for taking the lead in this.

**Pull request merged**
